### PR TITLE
fix: IndexOutOfRange on packet reading (Forge)

### LINKED ISSUE #2652: [BUG] Crash after join the server
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.1 Forge 47.2.19

### Console Client Version

20240114-240

### Expected Behavior

Able to connect to the server and send messages normally

### Actual Behavior

After the `Type '/quit' to leave the server.` output, the client crashes with InvalidDataException

### Steps to Reproduce the bug

1. Download [Forge server starter](https://www.curseforge.com/minecraft/mc-mods/forge-server-starter/download)
2. Install 1.20.1 with forge version 47.2.19
3. Start the server and connect it with a client

### Attach screenshot here (If applicable)

_No response_

### Anythings that could help diagnosing the bug

Log from client

```txt

Received FML3 Server Mod Data List
Received FML2 Server Mod List
Sending back FML2 Client Mod List
Acknowledging FML2 Server Registry: minecraft:command_argument_type
Acknowledging FML2 Server Registry: minecraft:recipe_serializer
{"enforcesSecureChat":true,"forgeData":{"channels":[],"mods":[],"truncated":false,"fmlNetworkVersion":3,"d":"^\u0000\u0000ࠄ㐤獋㙖⹌ᦘ̺⸱恤䒸⡑⛧沮婙㨹牥ఈㄵচ₀沮婙㨹牥ఈㄵচ偀泀岛㊳䄃㊜倱⭋眦湫Მ㒺杮戆䂸⠁ܰⶎ崚ᢁㄮ\u0002"},"description":{"text":"A Minecraft Server"},"players":{"max":20,"online":0},"version":{"name":"1.20.1","protocol":763}}
Server is running Forge with 2 mods.
Mod list:
  minecraft v1.20.1
  forge vANY
Server version : 1.20.1 (protocol v763, with Forge)
Acknowledging FML2 Server Registry: minecraft:sound_event
Acknowledging FML2 Server Registry: minecraft:particle_type
Acknowledging FML2 Server Registry: minecraft:villager_profession
Acknowledging FML2 Server Registry: minecraft:item
Acknowledging FML2 Server Registry: minecraft:potion
Acknowledging FML2 Server Registry: minecraft:painting_variant
Acknowledging FML2 Server Registry: forge:fluid_type
Acknowledging FML2 Server Registry: minecraft:block_entity_type
Acknowledging FML2 Server Registry: forge:display_contexts
Acknowledging FML2 Server Registry: minecraft:block
Acknowledging FML2 Server Registry: forge:entity_data_serializers
Acknowledging FML2 Server Registry: minecraft:mob_effect
Acknowledging FML2 Server Registry: minecraft:stat_type
Acknowledging FML2 Server Registry: minecraft:menu
Acknowledging FML2 Server Registry: minecraft:enchantment
Acknowledging FML2 Server Registry: minecraft:fluid
Acknowledging FML2 Server Registry: minecraft:entity_type
Acknowledging FML2 Server Config: forge-server.toml
[MCC] Server was successfully joined.
Type '/quit' to leave the server.
[DEBUG] Receive JoinGame
[DEBUG] CanSendMessage = False
[DEBUG] SendPlayerSession MessageUUID = 0872c31f-c03e-4387-a54a-4c311a665a7b,  len(PublicKey) = 294, len(SignatureV2) = 1
[DEBUG] Receive DeclareCommands
> Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type DeclareCommands. (PacketID: 16, Protocol: 763, LoginPhase: False, InnerException: System.IndexOutOfRangeException).
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MinecraftClient.Protocol.Handlers.packet.s2c.DeclareCommands.ExtractRootCommand()
   at MinecraftClient.Protocol.Handlers.packet.s2c.DeclareCommands.Read(DataTypes dataTypes, Queue`1 packetData, Int32 protocolVersion)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePlayPackets(Int32 packetId, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Aborted
```

Log from Server

```
[11:44:23] [User Authenticator #1/INFO] [minecraft/ServerLoginPacketListenerImpl]: UUID of player oldkingOK is *
[11:44:24] [Netty Server IO #12/ERROR] [ne.mi.ne.si.IndexedMessageCodec/SIMPLENET]: Received empty payload on channel fml:handshake
[11:44:25] [Server thread/INFO] [minecraft/PlayerList]: oldkingOK[/127.0.0.1:60418] logged in with entity id 227 at (-37.5, 60.0, 71.5)
[11:44:26] [Server thread/INFO] [minecraft/MinecraftServer]: oldkingOK joined the game
[11:44:27] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: QQbot lost connection: Disconnected
[11:44:27] [Server thread/INFO] [minecraft/MinecraftServer]: oldkingOK left the game
```

### Device

Desktop

### Operating System

Linux

### Server Address (If applicable)

_No response_

### PR DESCRIPTION
**Pull request by oldkingOK**
Fix #2652 

Add two missing forge Command Packet Parsers, which won't affect the vanilla parsers. 
The ids of the two Command Packet Parsers `forge:enum` and `forge:modid` [Forge once added in order](https://github.com/MinecraftForge/MinecraftForge/blob/19f8d2a7937dc7968ecbef2f9785687193fcd210/src/main/java/net/minecraftforge/common/ForgeMod.java#L175) are the maximum value of the Vanilla Parser id plus 1 or plus 2. `forge:enum` has a [String Type argument](https://wiki.vg/Command_Data#forge:enum). The specific id is from [wiki.vg](https://wiki.vg/Command_Data) or Forge-generated minecraft source code `net.minecraft.commands.synchronization.ArgumentTypeInfos` (Thanks to @kitUIN).

The table of version and id correspondences is shown below.

<table>
    <tr>
        <td>Version</td>
        <td>Protocol Version</td>
        <td><code>forge:enum</code> id</td>
        <td>Documented</td>
    </tr>
    <tr>
        <td>1.19</td>
        <td>759</td>
        <td>50</td>
        <td><a href=https://wiki.vg/index.php?title=Command_Data&diff=17551&oldid=17429>True</a></td>
    </tr>
    <tr>
        <td>1.19.1</td>
        <td>760</td>
        <td>50</td>
        <td>False</td>
    </tr>
    <tr>
        <td>1.19.2</td>
        <td>760</td>
        <td>50</td>
        <td>False</td>
    </tr>
    <tr>
        <td>1.19.3</td>
        <td>761</td>
        <td>50</td>
        <td><a href=https://wiki.vg/index.php?title=Command_Data&diff=prev&oldid=17946>True</a></td>
    </tr>
    <tr>
        <td>1.19.4</td>
        <td>762</td>
        <td>50</td>
        <td><a href=https://wiki.vg/index.php?title=Command_Data&diff=next&oldid=17946>True</a></td>
    </tr>
    <tr>
        <td>1.20</td>
        <td>763</td>
        <td>51</td>
        <td>False</td>
    </tr>
    <tr>
        <td>1.20.1</td>
        <td>763</td>
        <td>51</td>
        <td>False</td>
    </tr>
    <tr>
        <td>1.20.2</td>
        <td>764</td>
        <td>51</td>
        <td>False</td>
    </tr>
    <tr>
        <td>1.20.3</td>
        <td>765</td>
        <td>52</td>
        <td>False</td>
    </tr>
    <tr>
        <td>1.20.4</td>
        <td>765</td>
        <td>52</td>
        <td>False</td>
    </tr>
</table>

### CODE REVIEW

**Comment by oldkingOK** [comment]
It is ready for review or merge, thanks.

File: MinecraftClient/Protocol/Handlers/Packet/s2c/DeclareCommands.cs [hunk 1]
```diff
@@ -29,7 +29,19 @@ public static void Read(DataTypes dataTypes, Queue<byte> packetData, int protoco
...
+                            Protocol18Handler.MC_1_19_2_Version => parserId == 50,
+                            Protocol18Handler.MC_1_19_3_Version => parserId == 50,
+                            Protocol18Handler.MC_1_19_4_Version => parserId == 50,
+                            Protocol18Handler.MC_1_20_Version => parserId == 51,
+                            Protocol18Handler.MC_1_20_2_Version => parserId == 51,
+                            _ => false
+                        }) 
+                        parser = new ParserForgeEnum(dataTypes, packetData);
+
+                    else if (protocolVersion <= Protocol18Handler.MC_1_19_2_Version)
```
[the remark this answers is not in the document]
Comment (oldkingOK) [reply MinecraftClient/Protocol/Handlers/Packet/s2c/DeclareCommands.cs:44]: Forge's parser id changed in 1.20 and 1.20.1, while the Vanilla's didn't change a lot. I think putting it in the switch block will create another large `else if` branches for determining the version, because each one of which needs to implement the Vanilla parsers.

File: MinecraftClient/Protocol/Handlers/Packet/s2c/DeclareCommands.cs [hunk 2]
```diff
@@ -92,6 +94,16 @@ public static void Read(DataTypes dataTypes, Queue<byte> packetData, int protoco
...
+                            50 => protocolVersion == Protocol18Handler.MC_1_19_4_Version ?
+                              new ParserForgeEnum(dataTypes, packetData) :
+                              new ParserEmpty(dataTypes, packetData),
+                            51 => (protocolVersion >= Protocol18Handler.MC_1_20_Version &&
+                                   protocolVersion <= Protocol18Handler.MC_1_20_2_Version) ? // 1.20 - 1.20.2
+                              new ParserForgeEnum(dataTypes, packetData) :
+                              new ParserEmpty(dataTypes, packetData),
+                            52 => protocolVersion > Protocol18Handler.MC_1_20_2_Version ? // 1.20.2 +
+                              new ParserForgeEnum(dataTypes, packetData) :
+                              new ParserEmpty(dataTypes, packetData),
```
Comment (ReinforceZwei) [inline MinecraftClient/Protocol/Handlers/Packet/s2c/DeclareCommands.cs:106]: There will be a new switch block for 1.20.3+, so would you mind removing the 1.20.3+ forge parser in this PR and add it back once the 1.20.3/4 PR is merged?

Comment (oldkingOK) [reply MinecraftClient/Protocol/Handlers/Packet/s2c/DeclareCommands.cs:106]: Okay, it's done.

Comment (milutinke) [reply MinecraftClient/Protocol/Handlers/Packet/s2c/DeclareCommands.cs]: > Okay, it's done.

I just merged the 1.20.3 branch, please pull from master in to your branch and then re-add anything that needs to be added.

**Comment by milutinke** [comment]
Is this ready for merging?

**Comment by oldkingOK** [comment]
It is ready for merging, thanks.

**Comment by milutinke** [comment]
Merged. thanks for your contribution
